### ISSUE TITLE
Show bands of QgsRasterRenderers in profile panel

### ISSUE THREAD

**Issue by jakimowb** [EnMAP-Box/qgispluginsupport#1]
Show bands of linked QgsRasterLayers in Spectral Profile Plot

Nice reference implementation by @janzandr at:
https://bitbucket.org/hu-geomatics/enmap-box/commits/8a06f371ced0 
https://bitbucket.org/hu-geomatics/enmap-box/commits/3c97f04bd494731b2d0eb5cf362309f50bffe0c7

Modification:
- generic concept to handle multiple raster layers

**Comment by janzandr** [comment]
If you like, you can take over and modify, but I'm not sure if multiple raster layers would make too much sense, because of all the RGB bars in the plot.

**Comment by jakimowb** [comment]
The cases I can images are two or more canvases,

1. 2+ multi-color renderers to compare True Color and SWIR visualization
2. 2+ single band grey / pseudocolor renderers to compare NDVI values of different dates / products

**Comment by janzandr** [comment]
Yeah, maybe, then go for it.
