### ISSUE TITLE
[SpectralLibraryUtils] SpectralLibraryUtils.writeToSource is creates wrong CRS 

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/qgispluginsupport#54]
How to reproduce:

```
from enmapbox import initAll
from enmapbox.qgispluginsupport.qps.speclib.core.spectrallibrary import SpectralLibraryUtils
from enmapbox.testing import start_app
from enmapboxtestdata import landcover_point
from qgis._core import QgsVectorLayer

start_app()
initAll()

layer = QgsVectorLayer(landcover_point)
filenameCopy = 'copy.gpkg'
SpectralLibraryUtils.writeToSource(layer, filenameCopy)
layerCopy = QgsVectorLayer(filenameCopy)

print('CRS1:', layer.crs().authid(), layer.crs().toWkt())
print('CRS2:', layerCopy.crs().authid(), layerCopy.crs().toWkt())

assert layer.crs().authid() == layerCopy.crs().authid()
```
Python prints:

```
CRS1: EPSG:32633 PROJCS["WGS 84 / UTM zone 33N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",15],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32633"]]
CRS2:  GEOGCS["Undefined geographic SRS",DATUM["unknown",SPHEROID["unknown",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]]
```

**Comment by janzandr** [comment]
Thanks @jakimowb, the code snipped in the issue description runs successfully now.
Unfortunately, if I change `filenameCopy = 'copy.gpkg'` to `filenameCopy = 'copy.geojson'` it fails again.

Python prints:
```
CRS1: EPSG:32633 PROJCS["WGS 84 / UTM zone 33N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",15],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32633"]]
CRS2: EPSG:4326 GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
```

**Comment by jakimowb** [comment]
I think already had to mention this a couple of times before.
By definition, geojson is WGS84 Lat/Lon (see https://datatracker.ietf.org/doc/html/rfc7946)

>    GeoJSON is a geospatial data interchange format based on JavaScript
>    Object Notation (JSON).  It defines several types of JSON objects and
>    the manner in which they are combined to represent data about
>    geographic features, their properties, and their spatial extents.
>    GeoJSON uses a geographic coordinate reference system, World Geodetic
>    System 1984, and units of decimal degrees.
>

**Comment by janzandr** [comment]
Are you aware of the fact, that QGIS is able to do that?

For testing: just open a GeoPackage in QGIS and export it as GeoJSON:
![image](https://github.com/EnMAP-Box/qgispluginsupport/assets/45030715/8114015b-7df7-4773-80e8-4f2d39515e0f)

![image](https://github.com/EnMAP-Box/qgispluginsupport/assets/45030715/29ac9ff9-66ea-4cb4-8cb7-f468d008cea7)

**Comment by janzandr** [comment]
It would really be a pitty, if the EnMAP-Box wouldn't support the most important human-readable vector format, while standard QGIS is perfectly capable doing so.

**Comment by jakimowb** [comment]
The problem is that other software might fail to read such geojsons that violate rfc7946. E.g. many javascript libs expect it. 
What is the problem of getting WGS84 coodinates, as expected in rfc7946?

**Comment by janzandr** [comment]
1. If your external software needs EPSG:4326, you can easily reproject to EPSG:4326 using QGIS functionality.
2. External software issues should not limit the EnMAP-Box functionality compared to QGIS functionaliy.
3. I think the "external software can't handle it" argument is quit weak. If we would consistently follow this argumentation, we would also need to limit the creation options for the GTiff raster format, because external software like SNAP toolbox doesn't support everything QGIS/DGAL supports.

**Comment by janzandr** [comment]
I would recommend a new **forceWgs84** keyword, which defaults to **True** to match the **rfc7946** standard.
All the EnMAP-Box algorithms would use:
`SpectralLibraryUtils.writeToSource(library, filename, forceWgs84=False)`

**Comment by jakimowb** [comment]
Try to open your geojson here https://geojson.io to understand what I mean ;-) 
If you like to save your geojson different to RFC7946, you already can do with PyQGIS / QGIS. But we should not promote this, as it leads to problems. 
I still don't understand why there should be a need to save geojsons (and in particular Speclibs) in a CRS different than EPSG:4326?

**Comment by janzandr** [comment]
> I still don't understand why there should be a need to save geojsons (and in particular Speclibs) in a CRS different than EPSG:4326?

When exporting a vector layer in QGIS as GeoTiff, the original CRS is kept. This is the default behaviour. 
Exporting a vector layer using EnMAP-Box SpectralLibraryUtils.writeToSource is silently altering the CRS, which will for sure introduce some kind of accuracy loss.

I mean, I would expect that EnMAP-Box and QGIS default behaviour should match.

Are you mainly against it, because it is hard to implement? I could understand this. Otherwise I don't see a point, that the EnMAP-Box should silently alter vector geometries (it's kind of brutal :-))).

**Comment by jakimowb** [comment]
The default should be to write with [`RFC7946=YES`](https://gdal.org/drivers/vector/geojson.html#rfc-7946-write-support). I'll add some options that allow you to provide the OGR writing options to write it with obsolete GeoJSON 2008. (Which relevant software does _not_ support GTiff with band interleave?)

**Comment by janzandr** [comment]
> Which relevant software does not support GTiff with band interleave?

E.g., you can't open a band-interleaved and LZW-compressed GTiff in SNAP toolbox.

**Comment by jakimowb** [comment]
@janzandr `SpectralLibraryUtils.writeToSource(sl1, path4, rfc7946=False)`
