### ISSUE TITLE
SpatialPoint.toPixel gives wrong pixel coordinates

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/qgispluginsupport#66]
If the map coordinate corresponds to a negative pixel coordinate, the returned pixel coordinate is wrong (i.e. off by 1 pixel).

The calculated subpixel location is correct:
![image](https://github.com/user-attachments/assets/2ef21dfc-3b41-4bef-bf55-bf92307eb852)

But the int-casted result is wrong:
![image](https://github.com/user-attachments/assets/592460e6-7c0a-40b6-a2a0-c378febfd849)

E.g., fo a given a subpixel location of -0.5, we would expect a int-casted location of -1, but a location of 0 is returned.
This is because of the int-casting, which is not correct, in case of negative subpixel location.
Note that int(0.5) and int(-0.5) are both equal to 0.
![image](https://github.com/user-attachments/assets/fc92f1bc-6ecf-483a-a3c3-f67e8fe947de)

**Comment by jakimowb** [comment]
Yes, needs to be floored.
